### PR TITLE
SenNetwork 116

### PR DESCRIPTION
**Pull request by benbieler**
Use doctrine fixtures bundle / apply symfony-php unit-bridge.

### CODE REVIEW

**Comment by Ma27** [comment]
I think, that you will agree that it is impossible to merge all of those merge commits ;)

**Comment by Ma27** [comment]
and another thing: please prevent chaning the file mode of edited files

**Comment by benbieler** [comment]
Ok, sry

**Comment by Ma27** [comment]
well, it's ok, git isn't very simple to apply ;)

**Comment by Ma27** [comment]
I've squashed your commits into one and fixed the composer.json filemode.
now I'll fix the merge commits

**Comment by Ma27** [comment]
in order to avoid those unnecessary merge commits, please use *git pull --rebase*

**Pull request merged**
